package lester.first.kiss.quest.java.edition;

public class Cinematicas {
    public void delay(int seconds) {
        try {
            Thread.sleep(seconds * 1000);
        } catch (InterruptedException e) {
            System.out.println("Error en delay: " + e.getMessage());
        }
    }

    public void intro(){
        System.out.println("\nEsta es una historia de cuatro amigos, Lester, Dax, Hugh y Zohan\n");
        delay(1);
        System.out.println("Son cuatro chicos de 19 años, quienes se conocen desde la secundaria\n");
        delay(1);
        System.out.println("En la noche de año nuevo, Zohan se acordo de algo que le dijo Lester\n");
        delay(1);
        System.out.println("Una promesa, que tiene que cumplir en el presente año\n");
        delay(1);
        System.out.println("Por lo que rapidamente, Zohan toma su celular y decide hablar en el chat grupal de los amigos\n");
        delay(1);
        System.out.println("\n                  1 de Enero de 2015 - 12:30 am - Chat Grupal                     \n");
        delay(1);
        System.out.println("Zohan: @todos");
        delay(1);
        System.out.println("Zohan: Tengo un anuncio importante que dar");
        delay(1);
        System.out.println("Dax: ¿Que Paso?");
        delay(1);
        System.out.println("Dax: Me estaba durmiendo");
        delay(1);
        System.out.println("Zohan: Me acordé de algo de suma importancia");
        delay(1);
        System.out.println("Zohan: Es que no se si hacerlo más al rato");
        delay(1);
        System.out.println("Zohan: Porque necesito especialmente a Lester disponible");
        delay(1);
        System.out.println("Lester: Aqui estoy");
        delay(1);
        System.out.println("Lester: Dilo de una vez");
        delay(1);
        System.out.println("Zohan: Okey");
        delay(1);
        System.out.println("Zohan: @todos");
        delay(1);
        System.out.println("Zohan: Primero que nada");
        delay(1);
        System.out.println("Zohan: Feliz 2015");
        delay(1);
        System.out.println("Zohan: Ya es 2015");
        delay(1);
        System.out.println("Zohan: Y quiero hacerle un amable recordatorio a mi amigo Lester");
        delay(1);
        System.out.println("Zohan: Ya que dijo que haría algo especial este año");
        delay(1);
        System.out.println("Hugh: Al fin sacaras a Lester del Grupo?");
        delay(1);
        System.out.println("Zohan: Nop");
        delay(1);
        System.out.println("Zohan: Mi buen amigo Lester comento algo el 16 de agosto de 2013 a las 7:43 pm");
        delay(1);
        System.out.println("Zohan: Y cito");
        delay(1);
        delay(1);
        System.out.println("\n                 16 de Agosto de 2013 - 19:43 pm - Chat Grupal                   \n\n");
        delay(1);
        System.out.println("Lester: Aunque claro aún tengo presente el plan por si no doy mi primer beso antes de los 20");
        delay(1);
        System.out.println("Lester:  Ir a una convención");
        delay(1);
        System.out.println("Lester: Ver a una cosplayer de chica anime");
        delay(1);
        System.out.println("Lester: y ofrecerle unos $2000 para que me de un beso");
        delay(1);
        System.out.println("Lester: con todo respeto\n");
        delay(1);
        System.out.println("\n                  1 de Enero de 2015 - 01:00 am - Chat Grupal                    \n");
        delay(1);
        System.out.println("Dax: XD");
        delay(1);
        System.out.println("Dax: Ya se por donde va esto");
        delay(1);
        System.out.println("Zohan: Tic Tac Lester Tic Tac");
        delay(1);
        System.out.println("Lester: Se cancela");
        delay(1);
        System.out.println("Lester: Ni siquiera recordaba haber dicho eso");
        delay(1);
        System.out.println("Hugh: XD");
        delay(1);
        System.out.println("Hugh: Eres un reverendo pendejo Lester");
        delay(1);
        System.out.println("Zohan: No Lester");
        delay(1);
        System.out.println("Zohan: Ya no hay vuelta atrás");
        delay(1);
        System.out.println("Zohan: Te quedan 50 días Lester");
        delay(1);
        System.out.println("Zohan: Lo que quedaba de 2013 no hiciste nada");
        delay(1);
        System.out.println("Zohan: y en 2014 tampoco");
        delay(1);
        System.out.println("Zohan: Y ya solo te quedan menos de 2 meses Lester");
        delay(1);
        System.out.println("Zohan: El tiempo corre");
        delay(1);
        System.out.println("\nLester cumple 20 años dentro de 50 dias\n");
        delay(1);
        System.out.println("Asi que como dijo Zohan\n");
        delay(1);
        System.out.println("EL TIEMPO CORRE\n");
    }

    public void fiestaSalir(){
        System.out.println("\nTe escapas a escondidas de tu casa\n");
        delay(1);
        System.out.println("Tomas el metro para llegar al centro de la ciudad\n");
        delay(1);
        System.out.println("Entras a la primera discoteca que ves\n");
        delay(1);
        System.out.println("La estas pasando excelente\n");
        delay(1);
        System.out.println("Parece que se acercan unas chicas interesadas en ti\n");
        delay(1);
        System.out.println("Es hora de usar tus habilidades de carisma\n");
        delay(1);
    }
    
    public void burgerScene(Ligue ligue){
        delay(1);
        System.out.println("\nEstas teniendo una amena cita con " +ligue.getNombre()+"\n");
        delay(1);
        System.out.println("Estas apunto de comerte una Cowboy Rodeo Burger\n");
        delay(1);
        System.out.println("Ves como escurre esa Salsa BBQ en los Aros de Cebolla\n");
        delay(1);
        System.out.println("Y de repente\n");
        delay(1);
        System.out.println("Empiezas a notar un fuerte olor a Sebo, cerca de ti\n");
        delay(1);
        System.out.println("???: Oye tú");
        delay(1);
        System.out.println("???: Esa Cowboy Rodeo es mia");
        delay(1);
        System.out.println("Entonces el Sujeto Seboso te arrebata la hamburgesa\n");
    }

    public void reclamarSeboso(){
        delay(1);
        System.out.println("Lester: Oye Seboso, esa es mi hamburguesa");
        delay(1);
        System.out.println("Sujeto Seboso: ¿Como me dijiste?");
        delay(1);
        System.out.println("Lester: Que te vayas a bañar y me devuelvas mi hamburguesa");
        delay(1);
        System.out.println("Sujeto Seboso: ¿Y si no quiero?");
        delay(1);
        System.out.println("Lester: No es que no quieras");
        delay(1);
        System.out.println("Lester: Es que no puedes");
        delay(1);  
        System.out.println("Lester: Porque yo compre esa hamburguesa, con mi dinero"); 
        delay(1);
        System.out.println("Lester: Asi que devuelveme mi hamburguesa, y largate");
        delay(1);
        System.out.println("Lester: ¡MALDITO SEBOSO Y OBESO DE MIERDA!");
        delay(1);
        System.out.println("Sujeto Seboso: ¡¿QUE DIJISTE?!");
        delay(1);
        System.out.println("El Sujeto Seboso intenta darte un punietazo\n");
        delay(1);
        System.out.println("Pero gasto toda su energia en ello\n");
        delay(1);
        System.out.println("Y al final no te hizo nada de daño\n");
        delay(1);
        System.out.println("El Sujeto Seboso se cansa y se va del lugar\n");
    }
       
    public void badEnding(){
        delay(1);
        System.out.println("\n                        Unos Meses Despues                   \n");
        delay(1);
        System.out.println("\n             14 de Marzo de 2015 - 16:00 pm - Super Geek Fest                     \n");
        delay(1);
        System.out.println("Zohan: Muy bien");
        delay(1);
        System.out.println("Zohan: Ya llegamos al Super Geek Fest");
        delay(1);
        System.out.println("Zohan: ¿Estas Listo Lester?");
        delay(1);
        System.out.println("Lester: MmMmMmMmM");
        delay(1);
        System.out.println("\nVes nerviosamente a Hugh a quien le importas un comino pero ahi esta\n");
        delay(1);
        System.out.println("Luego ves nerviosamente a Dax quien trato de ayudarte pero fallo estrepitosamente\n");
        delay(1);
        System.out.println("Ves que ambos te estan mirando de una manera bastante peculiar, como si estuviaran aguantando la respiración\n");
        delay(1);
        System.out.println("Lester: Chicos ¿Le Decimos?");
        delay(1);
        System.out.println("Zohan: Decirme que");
        delay(1);
        System.out.println("Lester: Te sere sincero Zohan");
        delay(1);
        System.out.println("Lester: No alcanze a ahorrar $2000 para pagarle a la cosplayer");
        delay(1);
        System.out.println("\nVes que Hugh y Dax se empiezan a reír fuertemente\n");
        delay(1);
        System.out.println("Zohan: ¡PUTA MADRE LESTER!\n");
        LesterFirstKissQuestJavaEdition.fin_juego = true;
    }

    public void normEnding(Personaje personaje){
        System.out.println("\n                        Unos Meses Despues                   \n");
        delay(1);
        System.out.println("\n             14 de Marzo de 2015 - 16:00 pm - Super Geek Fest                     \n");
        delay(1);
        System.out.println("Zohan: Muy bien");
        delay(1);
        System.out.println("Zohan: Ya llegamos al Super Geek Fest");
        delay(1);
        System.out.println("Zohan: ¿Estas Listo Lester?");
        delay(1);
        System.out.println("Lester: Eso creo");
        delay(1);
        System.out.println("Zohan: Okey, En base a este mapa, estamos en el centro y");
        delay(1);
        System.out.println("Zohan: ¡AY CARAJO!");
        delay(1);
        System.out.println("Zohan: ¡SON UN MONTON DE COSPLAYERS!");
        delay(1);
        System.out.println("Dax: Es una convención, genio");
        delay(1);
        System.out.println("Zohan: Lo sé pero va a estar dificíl econtrar a una cosplayer de chica anime");
        delay(1);
        System.out.println("Hugh: Lo que tenemos que hacer por el estupido de Lester");
        delay(1);
        System.out.println("\n                        Unas Horas Despues                  \n");
        delay(1);
        System.out.println("Zohan: Okey, esta es la Cosplayer No. 500 de chica anime");
        delay(1);
        System.out.println("Zohan: Muy Bien Lester ya sabes que decir campeón");
        delay(1);
        System.out.println("Lester: MmMmMmMmM");
        delay(1);
        System.out.println("Lester: No lo se Zohan");
        delay(1);
        System.out.println("Lester: Empiezo a creer que esto es una perdida de tiempo");
        delay(1);
        System.out.println("\nVes lentamente como Zohan te da una cachetada\n");
        delay(1);
        System.out.println("Lester: Auch");
        delay(1);
        System.out.println("Zohan: Alivianate Bastardo");
        delay(1);
        System.out.println("Zohan:  Ya llegamos aquí y no tienes nada que perder ¿si o no?");
        delay(1);
        System.out.println("Dax: Si");
        delay(1);
        System.out.println("Hugh: Va a perder o $2000 o su dignidad");
        delay(1);
        System.out.println("Zohan: Callate Hugh");
        delay(1);
        System.out.println("Zohan:  Que dices Lester ¿Lo haras o eres un cobarde?");
        delay(1);
        System.out.println("Lester: Esta bien");
        delay(1);
        System.out.println("\nTe acercas lentamente a la cosplayer, estas congelado y no sabes que decir\n");
        delay(1);
        System.out.println("Lester: MmMmMmMm");
        delay(1);
        System.out.println("Lester: Oye Amiga");
        delay(1);
        System.out.println("Lester: MmMmMmMm");    
        delay(1);
        System.out.println("Cosplayer de Chica Anime: ¿Que se te ofrece amigo?");
        delay(1);
        System.out.println("Lester: MmMmMmMm");
        delay(1);
        System.out.println("Lester: No se si sea posible que me des unnnnn");
        delay(1);
        System.out.println("Lester: MmMmMmMm");        
        delay(1);
        System.out.println("Zohan: Carajo, Lester se trabó");
        delay(1);
        System.out.println("Dax: Se le olvidaron todos los consejos que le di");
        delay(1);
        System.out.println("Hugh: Que perdedor");
        delay(1);
        System.out.println("Cosplayer de Chica Anime: ¿Un que?");
        delay(1);
        System.out.println("Lester: U-un Beso a cambio d-de $2000");
        delay(1);
        System.out.println("Cosplayer de Chica Anime: ...");
        delay(5);
        System.out.println("\nEstas demasiado nervioso porque se esta tardando en responder\n");
        delay(1);
        System.out.println("Cosplayer de Chica Anime: Va ¿Porqué no?");
        personaje.resDinero(2000);
        LesterFirstKissQuestJavaEdition.primer_beso = true;
        delay(1);
        System.out.println("Zohan: Lo logró, ese bastardo lo logró");
        delay(1);
        System.out.println("Dax: Parece que alguien se tiene que retractar por lo que dijo hace rato");
        delay(1);
        System.out.println("Hugh: Por como lo hizo, no lo creo");
        delay(1);
        System.out.println("\nEntraste en un extasís, al fin diste tu primer beso\n");
        delay(1);
        System.out.println("Lester: ¡CHICOS! ¡LO LOGRE!\n");
        LesterFirstKissQuestJavaEdition.fin_juego = true;
    }

    public void noviaEscena(Ligue ligue){
        delay(1);
        System.out.println("\n               En ese mismo momento                   \n");
        delay(1);
        System.out.println("Lester: Oye " + ligue.getNombre());
        delay(1);
        System.out.println(ligue.getNombre() + ": Dime ¿Qué Ocurre?");
        delay(1);
        System.out.println("Lester: Es que, bueno, tu sabes");
        delay(1);
        System.out.println("Lester: Ya llevamos buen rato saliendo");
        delay(1);
        System.out.println("Lester: y yo me preguntaba");
        delay(1);
        System.out.println("Lester: ...");
        delay(1);
        System.out.println("Lester: MmMmMmMmM");
        delay(1);
        System.out.println("\nEstas congelado, tienes miedo, la incertidumbre te provoca inquietud\n");
        delay(1);
        System.out.println(ligue.getNombre() + ": Lester ¿Qué Pasa?");
        delay(1);
        System.out.println("\nEscuchar la voz de " + ligue.getNombre() + ", viendo su preocupación, te hace despertar\n");
        delay(1);
        System.out.println("Lester: "+ ligue.getNombre());
        delay(1);
        System.out.println("Lester: ¿Quisieras ser mi novia?");
        delay(1);
        System.out.println(ligue.getNombre() + ": ...");
        delay(5);
        System.out.println("\nEstas demasiado nervioso porque se esta tardando en responder\n");
        delay(1);
        System.out.println(ligue.getNombre() + ": Si");
        delay(1);
        System.out.println(ligue.getNombre() + ": Si quiero ser tu novia");
        delay(1);
        System.out.println("\nNo lo puedes creer, lo lograste, quisieras que tus amigos estuvieran aqui para verlo \n");
        delay(1);
        System.out.println("\nVes lentamente como " + ligue.getNombre() + " se avalanza sobre ti\n");
        delay(1);
        System.out.println("\nY\n");
        LesterFirstKissQuestJavaEdition.primer_beso = true;
        delay(1);
        System.out.println("\nEntraste en un extasís, al fin diste tu primer beso\n");
        delay(1);
        System.out.println("Lester: (Wow)");
        delay(1);
        System.out.println("Lester: (Lo Logré)\n");
        delay(1);
    }

    public void goodEnding(Ligue ligue){
        delay(1);
        System.out.println("\n                        Un Anio Despues                   \n");
        delay(1);
        System.out.println("\nEstas apunto de celebrar el primer aniversario que estas junto a "+ ligue.getNombre()+"\n");
        delay(1);
        System.out.println(ligue.getNombre()+": ¿Ya estas listo amor?");
        delay(1);
        System.out.println("Lester: Si ¿y tú?");
        delay(1);
        System.out.println(ligue.getNombre()+": Aun me falta maquillarme, esperame");
        delay(1);
        System.out.println("Lester: Okey");
        delay(1);
        System.out.println("\nDecides aprovechar el tiempo para hablar con tus amigos\n");
        delay(1);
        System.out.println("Abres chat grupal que tienes con tus amigos\n");
        delay(1);
        System.out.println("Lester: Bueno Chicos, hoy cumplo un año que estoy con "+ ligue.getNombre() + " y la verdad les quiero agradecer");
        delay(1);
        System.out.println("Lester: Primero, Gracias Zohan, porque si no me hubieras puesto este absurdo reto");
        delay(1);
        System.out.println("Lester: No hubiera conocido a una maravillosa persona");
        delay(1);
        System.out.println("Zohan: De nada, para eso estamos Lester");
        delay(1);
        System.out.println("Lester: Segundo, Gracias Dax, por apoyarme y darme consejos");
        delay(1);
        System.out.println("Dax: No hay nada que agradecer Lester, para eso estamos");
        delay(1);
        System.out.println("Lester: y por ultimo gracias Hugh, se que no te importo, pero almenos estuviste ahi");
        delay(1);
        System.out.println("Lester: y por eso te lo agradezco");
        delay(1);
        System.out.println("Hugh: Okey");
        delay(1);
        System.out.println("Lester: Bueno, ya me voy, gracias por todo chicos");
        delay(1);
        System.out.println("\nTe desconectas para salir con " + ligue.getNombre() +"\n");
        delay(1);
        System.out.println("Zohan: Bro, realmente hicimos crecer a Lester!");
        delay(1);
        System.out.println("Dax: Y si, quien crería que Lester ya tiene novia");
        delay(1); 
        System.out.println("Hugh: Yo hubiera apostado mi casa a que moría virgen\n");
        LesterFirstKissQuestJavaEdition.fin_juego = true;
    }
}